services:
  iot_clients_1:
    build:
      dockerfile: Dockerfile
      context: ./sensors
    depends_on:
      mytb:
        condition: service_started
    environment:
      BROKER_TOKEN: ${BROKER_TOKEN_1}
  
  iot_clients_2:
    build:
      dockerfile: Dockerfile
      context: ./sensors
    depends_on:
      mytb:
        condition: service_started
    environment:
      BROKER_TOKEN: ${BROKER_TOKEN_2}

  iot_clients_3:
    build:
      dockerfile: Dockerfile
      context: ./sensors
    depends_on:
      mytb:
        condition: service_started
    environment:
      BROKER_TOKEN: ${BROKER_TOKEN_3}
  
  iot_clients_4:
    build:
      dockerfile: Dockerfile
      context: ./sensors
    depends_on:
      mytb:
        condition: service_started
    environment:
      BROKER_TOKEN: ${BROKER_TOKEN_4}
  
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ./mytb/data:/data
      - ./mytb/logs:/var/log/thingsboard